"""phase B: discipline score fields + user aggregates

Revision ID: 082b82ed3d8c
Revises: 4840809fb2af
Create Date: 2026-07-14 13:07:11.901472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082b82ed3d8c'
down_revision = '4840809fb2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discipline_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_risk_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('no_stop_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('oversize_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('revenge_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rule_violations', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_trades_all', sa.Integer(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('trades_with_stops_all', sa.Integer(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('blown_count', sa.Integer(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('sessions_scored', sa.Integer(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('discipline_sum', sa.Float(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_column('discipline_sum')
        batch_op.drop_column('sessions_scored')
        batch_op.drop_column('blown_count')
        batch_op.drop_column('trades_with_stops_all')
        batch_op.drop_column('total_trades_all')

    with op.batch_alter_table('session_scores', schema=None) as batch_op:
        batch_op.drop_column('rule_violations')
        batch_op.drop_column('revenge_count')
        batch_op.drop_column('oversize_count')
        batch_op.drop_column('no_stop_count')
        batch_op.drop_column('avg_risk_pct')
        batch_op.drop_column('discipline_score')

    # ### end Alembic commands ###
