"""phase A: order engine fields on trades

Revision ID: 275caa01456b
Revises: 3cf1ea850321
Create Date: 2026-07-14 01:35:29.177028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275caa01456b'
down_revision = '3cf1ea850321'
branch_labels = None
depends_on = None


def upgrade():
    # NOT NULL columns carry a server_default so ADD COLUMN succeeds on a
    # trades table that already has rows (existing/historical trades).
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=False, server_default='open'))
        batch_op.add_column(sa.Column('order_type', sa.String(length=10), nullable=False, server_default='market'))
        batch_op.add_column(sa.Column('entry_order_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bar_sequence_created', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trail_distance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_anchor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exit_reason', sa.String(length=20), nullable=True))

    # Backfill: any pre-existing trade that already has an exit is closed.
    op.execute("UPDATE trades SET status = 'closed' WHERE exit_price IS NOT NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('exit_reason')
        batch_op.drop_column('trail_anchor')
        batch_op.drop_column('trail_distance')
        batch_op.drop_column('bar_sequence_created')
        batch_op.drop_column('entry_order_price')
        batch_op.drop_column('order_type')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
