"""phase B: missions + mission_attempts

Revision ID: 2ddcb1a56eb7
Revises: 082b82ed3d8c
Create Date: 2026-07-14 13:15:17.531876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddcb1a56eb7'
down_revision = '082b82ed3d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('difficulty_tier', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('is_daily_pool', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('mission_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('violations', sa.JSON(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('is_daily', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('challenge_date', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mission_attempts')
    op.drop_table('missions')
    # ### end Alembic commands ###
