"""phase A: leverage on trades

Revision ID: 4840809fb2af
Revises: 275caa01456b
Create Date: 2026-07-14 12:14:56.883284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4840809fb2af'
down_revision = '275caa01456b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leverage', sa.Float(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('leverage')

    # ### end Alembic commands ###
